version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  groups:
    minor-actions-dependencies:
      # GitHub Actions: Only group minor and patch updates (we want to carefully review major updates)
      update-types: [ minor, patch ]

- package-ecosystem: gomod
  directory: /
  allow:
    # Go: allow direct and indirect updates
    - dependency-type: all
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  schedule:
    interval: monthly
  groups:
    minor-go-dependencies:
      # Go: Only group minor and patch updates (we want to carefully review major updates)
      update-types: [ minor, patch ]
