// Copyright 2023 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// This file contains all counter metrics used within SVR2.
//
// They're created with the macro CREATE_COUNTER, which takes arguments:
//   * ns - namespace of the counter (generally, module name)
//   * varname - name of the variable used to reference this counter, must be
//     unique within the namespace (ns)
//   * name - name of the exported variable (actually, "ns.name")
//   * tags - set of tags associated with this variable, either empty `({})`, or
//     an initializer list `({{"foo", "bar"}, {"baz", "blah"}})` for tags
//     foo=bar, baz=blah.  Must be wrapped in parens.
//
// Once these counters are created here, they're used with the incantation:
//   COUNTER(ns, varname)->CounterFunction();
// IE:
//   COUNTER(sender, enclave_messages_sent)->IncrementBy(3);
//
// All counters created here will be exported to the host, even if they are
// zero.  This differs from error counts, which are exported only if non-zero.

CREATE_COUNTER(ecalls, host_messages_received, host_messages_received, ({}))
CREATE_COUNTER(ecalls, host_bytes_received, host_bytes_received, ({}))
CREATE_COUNTER(ecalls, init_calls, init_calls, ({}))

CREATE_COUNTER(sender, enclave_messages_sent, enclave_messages_sent, ({}))
CREATE_COUNTER(sender, enclave_bytes_sent, enclave_bytes_sent, ({}))

CREATE_COUNTER(core, host_requests_received, msgs_received, ({{"type", "host_request"}}))
CREATE_COUNTER(core, peer_msgs_received,     msgs_received, ({{"type", "peer_message"}}))
CREATE_COUNTER(core, timer_ticks_received,   msgs_received, ({{"type", "timer_tick"}}))
CREATE_COUNTER(core, invalid_msgs_received,  msgs_received, ({{"type", "invalid"}}))
CREATE_COUNTER(core, new_client_success, new_clients, ({{"outcome", "success"}}))
CREATE_COUNTER(core, new_client_failure, new_clients, ({{"outcome", "failure"}}))
CREATE_COUNTER(core, log_transactions_success, log_transactions, ({{"outcome", "success"}}))
CREATE_COUNTER(core, log_transactions_cancelled, log_transactions, ({{"outcome", "cancelled"}}))
CREATE_COUNTER(core, host_delete_success, host_delete, ({{"outcome", "success"}}))
CREATE_COUNTER(core, host_delete_failure, host_delete, ({{"outcome", "failure"}}))
CREATE_COUNTER(core, client_transaction_success, client_transaction, ({{"outcome", "success"}, {"method", "raft"}}))
CREATE_COUNTER(core, client_transaction_cancelled, client_transaction, ({{"outcome", "cancelled"}, {"method", "raft"}}))
CREATE_COUNTER(core, client_transaction_error, client_transaction, ({{"outcome", "error"}, {"method", "raft"}}))
CREATE_COUNTER(core, client_transaction_invalid, client_transaction, ({{"outcome", "invalid"}, {"method", "raft"}}))
CREATE_COUNTER(core, client_transaction_dne, client_transaction, ({{"outcome", "dne"}, {"method", "raft"}}))
CREATE_COUNTER(core, client_transaction_effect2response, client_transaction, ({{"outcome", "effect2response"}, {"method", "raft"}}))
CREATE_COUNTER(core, client_transaction_encrypterr, client_transaction, ({{"outcome", "encrypterr"}, {"method", "raft"}}))
CREATE_COUNTER(core, client_transaction_clientstate_success, client_transaction, ({{"outcome", "success"}, {"method", "clientstate"}}))
CREATE_COUNTER(core, client_transaction_clientstate_error, client_transaction, ({{"outcome", "error"}, {"method", "clientstate"}}))
CREATE_COUNTER(core, client_transaction_clientstate_encrypterr, client_transaction, ({{"outcome", "encrypterr"}, {"method", "clientstate"}}))
CREATE_COUNTER(core, raft_log_applied, raft_log_applied, ({}))

CREATE_COUNTER(client, created, created, ({}))
CREATE_COUNTER(client, closed, closed, ({}))
CREATE_COUNTER(client, new_dh_state, new_dh_state, ({}))
CREATE_COUNTER(client, key_rotate_success, key_rotate, ({{"outcome", "success"}}))
CREATE_COUNTER(client, key_rotate_failure, key_rotate, ({{"outcome", "failure"}}))
CREATE_COUNTER(client, attestation_refresh_success, attestation_refresh, ({{"outcome", "success"}}))
CREATE_COUNTER(client, attestation_refresh_failure, attestation_refresh, ({{"outcome", "failure"}}))

CREATE_COUNTER(peers, attestation_refresh_success, attestation_refresh, ({{"outcome", "success"}}))
CREATE_COUNTER(peers, attestation_refresh_failure, attestation_refresh, ({{"outcome", "failure"}}))

CREATE_COUNTER(raft, logs_committed, logs_committed, ({}))
CREATE_COUNTER(raft, logs_promised, logs_promised, ({}))
CREATE_COUNTER(raft, vote_requests_received, msgs_received, ({{"type", "vote_request"}}))
CREATE_COUNTER(raft, vote_responses_received, msgs_received, ({{"type", "vote_response"}}))
CREATE_COUNTER(raft, append_requests_received, msgs_received, ({{"type", "append_request"}}))
CREATE_COUNTER(raft, append_responses_received, msgs_received, ({{"type", "append_response"}}))
CREATE_COUNTER(raft, timeout_nows_received, msgs_received, ({{"type", "timeout_now"}}))
CREATE_COUNTER(raft, invalid_requests_received, msgs_received, ({{"type", "invalid"}}))
CREATE_COUNTER(raft, term_updated, term_updated, ({}))
CREATE_COUNTER(raft, term_increments, term_increments, ({}))
CREATE_COUNTER(raft, logs_append_success, logs_appended, ({{"outcome", "success"}}))
CREATE_COUNTER(raft, logs_append_failure, logs_appended, ({{"outcome", "failure"}}))
CREATE_COUNTER(raft, election_timeouts, election_timeouts, ({}))
CREATE_COUNTER(raft, appendentries_nomsg, appendentries_send, ({{"outcome", "nomsg"}}))
CREATE_COUNTER(raft, appendentries_inflight_send, appendentries_send, ({{"outcome", "inflight_send"}}))
CREATE_COUNTER(raft, appendentries_inflight_defer, appendentries_send, ({{"outcome", "inflight_defer"}}))
CREATE_COUNTER(raft, appendentries_send, appendentries_send, ({{"outcome", "send"}}))

CREATE_COUNTER(timeout, timeouts_created, timeouts_created, ({}))
CREATE_COUNTER(timeout, timeouts_run, timeouts_completed, ({{"outcome", "run"}}))
CREATE_COUNTER(timeout, timeouts_cancelled, timeouts_completed, ({{"outcome", "cancelled"}}))

CREATE_COUNTER(db2, ops_backup, ops, ({{"type", "backup"}}))
CREATE_COUNTER(db2, ops_restore, ops, ({{"type", "restore"}}))
CREATE_COUNTER(db2, ops_delete, ops, ({{"type", "delete"}}))
CREATE_COUNTER(db2, ops_expose, ops, ({{"type", "expose"}}))
CREATE_COUNTER(db2, ops_tries, ops, ({{"type", "tries"}}))
CREATE_COUNTER(db2, ops_unknown, ops, ({{"type", "unknown"}}))

CREATE_COUNTER(db3, ops_create, ops, ({{"type", "create"}}))
CREATE_COUNTER(db3, ops_evaluate, ops, ({{"type", "evaluate"}}))
CREATE_COUNTER(db3, ops_remove, ops, ({{"type", "remove"}}))
CREATE_COUNTER(db3, ops_query, ops, ({{"type", "query"}}))

CREATE_COUNTER(db4, ops_create, ops, ({{"type", "create"}}))
CREATE_COUNTER(db4, ops_restore1, ops, ({{"type", "restore1"}}))
CREATE_COUNTER(db4, ops_restore2, ops, ({{"type", "restore2"}}))
CREATE_COUNTER(db4, ops_remove, ops, ({{"type", "remove"}}))
CREATE_COUNTER(db4, ops_query, ops, ({{"type", "query"}}))
CREATE_COUNTER(db4, ops_rotate_start, ops, ({{"type", "rotate_start"}}))
CREATE_COUNTER(db4, ops_rotate_commit, ops, ({{"type", "rotate_commit"}}))
CREATE_COUNTER(db4, ops_rotate_rollback, ops, ({{"type", "rotate_rollback"}}))
CREATE_COUNTER(db4, client_err_UNKNOWN, client_errors, ({{"err", "UNKNOWN"}}))
CREATE_COUNTER(db4, client_err_UNSET, client_errors, ({{"err", "UNSET"}}))
CREATE_COUNTER(db4, client_err_OK, client_errors, ({{"err", "OK"}}))
CREATE_COUNTER(db4, client_err_INVALID_REQUEST, client_errors, ({{"err", "INVALID_REQUEST"}}))
CREATE_COUNTER(db4, client_err_MISSING, client_errors, ({{"err", "MISSING"}}))
CREATE_COUNTER(db4, client_err_ERROR, client_errors, ({{"err", "ERROR"}}))
CREATE_COUNTER(db4, client_err_RESTORE1_MISSING, client_errors, ({{"err", "RESTORE1_MISSING"}}))
CREATE_COUNTER(db4, client_err_VERSION_MISMATCH, client_errors, ({{"err", "VERSION_MISMATCH"}}))
CREATE_COUNTER(db4, client_err_NOT_ROTATING, client_errors, ({{"err", "NOT_ROTATING"}}))
CREATE_COUNTER(db4, client_err_ALREADY_ROTATING, client_errors, ({{"err", "ALREADY_ROTATING"}}))
CREATE_COUNTER(db4, client_err_MERKLE_FAILURE, client_errors, ({{"err", "MERKLE_FAILURE"}}))

CREATE_COUNTER(merkle, nodes, nodes, ({}))
CREATE_COUNTER(merkle, leaves, leaves, ({}))

CREATE_COUNTER(socketwrap, bytes_written, bytes_written, ({}))
CREATE_COUNTER(socketwrap, bytes_read, bytes_read, ({}))
CREATE_COUNTER(socketwrap, msgs_written, msgs_written, ({}))
CREATE_COUNTER(socketwrap, msgs_read, msgs_read, ({}))
CREATE_COUNTER(socketwrap, writeall_calls, writeall_calls, ({}))
CREATE_COUNTER(socketwrap, send_calls, send_calls, ({}))
CREATE_COUNTER(socketwrap, recv_calls, recv_calls, ({}))
CREATE_COUNTER(socketwrap, write_buffer_shrinks, write_buffer_shrinks, ({}))

CREATE_COUNTER(context, cpu_uncategorized, cpu, ({{"in", "uncategorized"}, {"action", "uncategorized"}}))
CREATE_COUNTER(context, cpu_client_encrypt, cpu, ({{"in", "client"}, {"action", "encrypt"}}))
CREATE_COUNTER(context, cpu_client_decrypt, cpu, ({{"in", "client"}, {"action", "decrypt"}}))
CREATE_COUNTER(context, cpu_client_hs_start, cpu, ({{"in", "client"}, {"action", "hs_start"}}))
CREATE_COUNTER(context, cpu_client_hs_finish, cpu, ({{"in", "client"}, {"action", "hs_finish"}}))
CREATE_COUNTER(context, cpu_peer_encrypt, cpu, ({{"in", "peer"}, {"action", "encrypt"}}))
CREATE_COUNTER(context, cpu_peer_decrypt, cpu, ({{"in", "peer"}, {"action", "decrypt"}}))
CREATE_COUNTER(context, cpu_peer_connect, cpu, ({{"in", "peer"}, {"action", "connect"}}))
CREATE_COUNTER(context, cpu_peer_connect2, cpu, ({{"in", "peer"}, {"action", "connect2"}}))
CREATE_COUNTER(context, cpu_peer_accept, cpu, ({{"in", "peer"}, {"action", "accept"}}))
CREATE_COUNTER(context, cpu_db_client_request, cpu, ({{"in", "db"}, {"action", "client_request"}}))
CREATE_COUNTER(context, cpu_db_repl_send, cpu, ({{"in", "db"}, {"action", "repl_send"}}))
CREATE_COUNTER(context, cpu_db_repl_recv, cpu, ({{"in", "db"}, {"action", "repl_recv"}}))
CREATE_COUNTER(context, cpu_db_hash, cpu, ({{"in", "db"}, {"action", "hash"}}))
CREATE_COUNTER(context, cpu_db_repl_merkle_hash, cpu, ({{"in", "db"}, {"action", "repl_merkle_hash"}}))
CREATE_COUNTER(context, cpu_db_repl_merkle_update, cpu, ({{"in", "db"}, {"action", "repl_merkle_update"}}))
CREATE_COUNTER(context, cpu_db3_new_keys, cpu, ({{"in", "db3"}, {"action", "new_keys"}}))
CREATE_COUNTER(context, cpu_db3_blind_evaluate, cpu, ({{"in", "db3"}, {"action", "blind_evaluate"}}))
CREATE_COUNTER(context, cpu_core_client_msg, cpu, ({{"in", "core"}, {"action", "client_msg"}}))
CREATE_COUNTER(context, cpu_core_peer_msg, cpu, ({{"in", "core"}, {"action", "peer_msg"}}))
CREATE_COUNTER(context, cpu_core_peer_rst, cpu, ({{"in", "core"}, {"action", "peer_rst"}}))
CREATE_COUNTER(context, cpu_core_host_msg, cpu, ({{"in", "core"}, {"action", "host_msg"}}))
CREATE_COUNTER(context, cpu_core_raft_msg, cpu, ({{"in", "core"}, {"action", "raft_msg"}}))
CREATE_COUNTER(context, cpu_core_e2e_txn_req, cpu, ({{"in", "core"}, {"action", "e2e_txn_req"}}))
CREATE_COUNTER(context, cpu_core_e2e_txn_resp, cpu, ({{"in", "core"}, {"action", "e2e_txn_resp"}}))
CREATE_COUNTER(context, cpu_core_repl_send, cpu, ({{"in", "core"}, {"action", "repl_send"}}))
CREATE_COUNTER(context, cpu_core_repl_recv, cpu, ({{"in", "core"}, {"action", "repl_recv"}}))
CREATE_COUNTER(context, cpu_core_committed_logs, cpu, ({{"in", "core"}, {"action", "committed_logs"}}))
CREATE_COUNTER(context, cpu_core_timer_tick, cpu, ({{"in", "core"}, {"action", "timer_tick"}}))
CREATE_COUNTER(context, cpu_core_host_database_req, cpu, ({{"in", "core"}, {"action", "host_db_req"}}))
CREATE_COUNTER(context, cpu_core_metrics, cpu, ({{"in", "core"}, {"action", "metrics"}}))
CREATE_COUNTER(context, cpu_core_connecting_to_raft_members, cpu, ({{"in", "core"}, {"action", "connecting_to_raft_members"}}))
CREATE_COUNTER(context, cpu_core_updating_group_time, cpu, ({{"in", "core"}, {"action", "updating_group_time"}}))
CREATE_COUNTER(context, cpu_core_raft_tick, cpu, ({{"in", "core"}, {"action", "raft_tick"}}))
CREATE_COUNTER(context, cpu_core_update_env_stats, cpu, ({{"in", "core"}, {"action", "update_env_stats"}}))
CREATE_COUNTER(context, cpu_core_update_last_applied_merkle, cpu, ({{"in", "core"}, {"action", "update_last_applied_merkle"}}))
CREATE_COUNTER(context, cpu_core_verify_last_applied_merkle, cpu, ({{"in", "core"}, {"action", "verify_last_applied_merkle"}}))
CREATE_COUNTER(context, cpu_raft_merkle_update, cpu, ({{"in", "raft"}, {"action", "merkle_update"}}))
CREATE_COUNTER(context, cpu_raft_merkle_verify, cpu, ({{"in", "raft"}, {"action", "merkle_verify"}}))
CREATE_COUNTER(context, cpu_test_database_entries, cpu, ({{"in", "core"}, {"action", "test_database_entries"}}))
CREATE_COUNTER(context, cpu_env_attest, cpu, ({{"in", "env"}, {"action", "attest"}}))
CREATE_COUNTER(context, cpu_env_evidence, cpu, ({{"in", "env"}, {"action", "evidence"}}))
CREATE_COUNTER(context, cpu_env_sendmessage, cpu, ({{"in", "env"}, {"action", "sendmessage"}}))
CREATE_COUNTER(context, cpu_sender_serialize, cpu, ({{"in", "sender"}, {"action", "serialize"}}))
CREATE_COUNTER(context, cpu_sender_send, cpu, ({{"in", "sender"}, {"action", "send"}}))
CREATE_COUNTER(context, cpu_socket_read_recv, cpu, ({{"in", "socketwrap"}, {"action", "read_recv"}}))
CREATE_COUNTER(context, cpu_socket_read_parse, cpu, ({{"in", "socketwrap"}, {"action", "read_parse"}}))
CREATE_COUNTER(context, cpu_socket_write_serialize, cpu, ({{"in", "socketwrap"}, {"action", "write_serialize"}}))
CREATE_COUNTER(context, cpu_socket_write_send, cpu, ({{"in", "socketwrap"}, {"action", "write_send"}}))
CREATE_COUNTER(context, cpu_timeout_timer_tick, cpu, ({{"in", "timeout"}, {"action", "timer_tick"}}))

CREATE_COUNTER(context, lock_core_raft, cpu, ({{"in", "core"}, {"action", "lock"}, {"lock", "core_raft"}}))
CREATE_COUNTER(context, lock_core_log_txns, cpu, ({{"in", "core"}, {"action", "lock"}, {"lock", "core_log_txns"}}))
CREATE_COUNTER(context, lock_core_e2e_txns, cpu, ({{"in", "core"}, {"action", "lock"}, {"lock", "core_e2e_txns"}}))
CREATE_COUNTER(context, lock_core_config, cpu, ({{"in", "core"}, {"action", "lock"}, {"lock", "core_config"}}))
CREATE_COUNTER(context, lock_groupclock, cpu, ({{"in", "groupclock"}, {"action", "lock"}, {"lock", "groupclock"}}))
CREATE_COUNTER(context, lock_timeout, cpu, ({{"in", "timeout"}, {"action", "lock"}, {"lock", "timeout"}}))
CREATE_COUNTER(context, lock_peermanager, cpu, ({{"in", "peer"}, {"action", "lock"}, {"lock", "peermanager"}}))
CREATE_COUNTER(context, lock_peer, cpu, ({{"in", "peer"}, {"action", "lock"}, {"lock", "peer"}}))
CREATE_COUNTER(context, lock_clientmanager, cpu, ({{"in", "client"}, {"action", "lock"}, {"lock", "clientmanager"}}))
CREATE_COUNTER(context, lock_client, cpu, ({{"in", "client"}, {"action", "lock"}, {"lock", "client"}}))
CREATE_COUNTER(context, lock_test, cpu, ({{"in", "test"}}))
CREATE_COUNTER(context, lock_socket_read, cpu, ({{"in", "socketwrap"}, {"action", "lock"}, {"lock", "read"}}))
CREATE_COUNTER(context, lock_socket_write, cpu, ({{"in", "socketwrap"}, {"action", "lock"}, {"lock", "write"}}))
CREATE_COUNTER(context, lock_testenv_sendmessage, cpu, ({{"in", "envtest"}, {"action", "lock"}, {"lock", "sendmessage"}}))
CREATE_COUNTER(context, lock_minimums_updateset, cpu, ({{"in", "minimums"}, {"action", "lock"}, {"lock", "updateset"}}))
CREATE_COUNTER(context, lock_minimums_updatevalue, cpu, ({{"in", "minimums"}, {"action", "lock"}, {"lock", "updatevalue"}}))
CREATE_COUNTER(context, lock_minimums_checkvalues, cpu, ({{"in", "minimums"}, {"action", "lock"}, {"lock", "checkvalues"}}))
CREATE_COUNTER(context, lock_minimums_copyvalues, cpu, ({{"in", "minimums"}, {"action", "lock"}, {"lock", "copyvalues"}}))
