name: CI
on: [push]

env:
  DOCKER_BUILD_ARGS: --cache-from type=gha --cache-to type=gha
  DOCKER_BUILDKIT: 1
  BUILDX_CONTAINER: container
  V: 1

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
      id-token: write

    steps:
      - name: Checkout main project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Expose Docker environmental variables for gha cache
        # This action takes in the ID tokens etc provided by the permissions,
        # as well as some environmental data, and exposes them to future steps
        # in the correct locations and formats for their use with the `gha`
        # GitHub Actions cache for Docker.
        uses: crazy-max/ghaction-github-runtime@3cb05d89e1f492524af3d41a1c98c83bc3025124 # v3.1.0

      - name: Setup Docker
        run: docker buildx create --use --name container --driver docker-container

      - name: Test
        run: make docker_enclave_test

      - name: Build
        run: make

      - name: Validate
        run: make docker_validate

      - name: Valgrind
        run: make docker_enclave_valgrind
